
name: Docker Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The name of the image.
      image_tag:
        required: true
        type: string
        description: The tag name.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      pull-requests: read
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to Docker registry
        run: |
          echo "LOGIN TO DOCKER REGISTRY"
          docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build . --file ./dockerfiles/Dockerfile --tag ${{ inputs.image_name }}:${{ inputs.image_tag }} --build-arg username=${{ github.actor }} --build-arg password=${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ inputs.image_name }}:${{ inputs.image_tag }}
