name: Update Manifest

on:
  workflow_call:
     inputs: 
      repository_name:
        type: string
        description: 'Name of the repository to update in the manifest'
        required: true
      version:
         type: string
         description: 'Version to be used for the repository'
         required: true 
jobs:
  update_manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout releases repo
        uses: actions/checkout@v3
        with:
          repository: dangi13/releases
          ref: main
          persist-credentials: true 
          token: ${{ secrets.PAT }} 

      - name: Update manifest dev.json
        id: update_manifest
        run: |
          jq '.["${{ inputs.repository_name }}"] = {"version": "'"${{ inputs.version }}'" }' manifests/dev.json > manifests/dev.json.tmp
          mv manifests/dev.json.tmp manifests/dev.json

      - name: Commit and push changes
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}+github-actions@github.com"
          git add manifests/dev.json
          git commit -m "Update ${{ inputs.repository_name }} version in dev.json to ${{ inputs.version }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }} 
